name: Publish Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:
  build_and_push:
    name: Build and push images to GHCR
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - name: Login to GHCR
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build and push images
        run: bash build.sh
        shell: bash