name: Publish Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:
  build_and_push:
    name: Build and push images to GHCR
    strategy:
      fail-fast: true
      matrix:
        version: ['2_7', '3_0', '3_1']
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - name: Login to GHCR
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a  # v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build and push images
        run: build.sh ${{ matrix.version }}
        shell: bash
