name: Build arm image for release

on:
  pull_request:

jobs:
  build_release_image:
    name: Build release on Ruby 4.x arm images
    uses: ./.github/workflows/build-app.yaml
    with:
      gitRef: ${{ github.head_ref }}
      appName: release
      rubyVersion: 4
    permissions:
      contents: read